name: Lint & Test

on: push

env:
  DEFAULT_BRANCH: main

jobs:
  test:
    name: Run lint and test
    runs-on: ubuntu-latest

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout git repository
        uses: actions/checkout@v2

      - name: Read .nvmrc
        run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc | grep -o "[^a-z].*")
        id: nvm

      - name: Setup node v${{ steps.nvm.outputs.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.nvm.outputs.NODE_VERSION }}

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Test
        run: yarn test
