"use strict";

const { error, off } = require("./levels");

module.exports = {
  extends: ["eslint:recommended"],
  rules: {
    curly: error,
    "no-console": error,
    "func-names": off,
    "array-bracket-newline": [error, "consistent"],
    "max-statements-per-line": [error, { max: 1 }],
    "no-array-constructor": error,
    "no-bitwise": error,
    "no-lonely-if": error,
    "no-negated-condition": error,
    "no-trailing-spaces": error,
    "no-unneeded-ternary": error,
    "no-whitespace-before-property": error,
    "prefer-object-spread": error,
    "spaced-comment": [error, "always"],
    "switch-colon-spacing": error,
    "wrap-regex": error,
    "arrow-spacing": [error, { before: true, after: true }],
    "no-duplicate-imports": error,
    "no-useless-rename": error,
    "no-var": error,
    "prefer-const": error,
    "prefer-spread": error,
    "prefer-template": error,
    "rest-spread-spacing": error,
    "default-case-last": error,
    "default-param-last": error,
    eqeqeq: error,
    "grouped-accessor-pairs": error,
    "no-alert": error,
    "no-else-return": error,
    "no-eq-null": error,
    "no-eval": error,
    "no-return-await": error,
    "no-restricted-imports": off,
    "consistent-return": [error, { treatUndefinedAsUnspecified: false }],
  },
};
